from domain.telemetry_feature import TelemetryFeature

LMU_FEATURE_MAP = {
    "GPS Time": TelemetryFeature.SESSION_TIME,
    "Lap": TelemetryFeature.LAP,
    "Lap Time": TelemetryFeature.LAP_TIME,
    "Lap Dist": TelemetryFeature.LAP_DISTANCE,
    "Best LapTime": TelemetryFeature.BEST_LAP_TIME,
    "Best Sector1": TelemetryFeature.BEST_SECTOR_1_TIME,
    "Best Sector2": TelemetryFeature.BEST_SECTOR_2_TIME,
    "Throttle Pos": TelemetryFeature.THROTTLE,
    "Brake Pos": TelemetryFeature.BRAKE,
    "Steering Pos": TelemetryFeature.STEERING,
    "Clutch Pos": TelemetryFeature.CLUTCH,
    "Gear": TelemetryFeature.GEAR,
    "Ground Speed": TelemetryFeature.SPEED,
    "Engine RPM": TelemetryFeature.RPM,
    "Fuel Level": TelemetryFeature.FUEL,
    "Tyres Wear": TelemetryFeature.TYRE_WEAR,
    "TyresPressure": TelemetryFeature.TYRE_PRESSURE,
    "Tyres Temperature": TelemetryFeature.TYRE_TEMPERATURE,
    "TyresCompound": TelemetryFeature.TYRE_COMPOUND,
    "Brakes Temp": TelemetryFeature.BRAKE_TEMPERATURE,
    "Track Temperature": TelemetryFeature.TRACK_TEMPERATURE,
    "Virtual Energy": TelemetryFeature.BATTERY,
    "In Pits": TelemetryFeature.IN_PITS,
    "GPS Latitude": TelemetryFeature.GPS_LATITUDE,
    "GPS Longitude": TelemetryFeature.GPS_LONGITUDE,
}
